# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install adonis   
      run: npm i @adonisjs/cli@4.0.12
      
    - name: Setup test database
      run: | 
        cd server
        mysql -u root -p datrootabase -h 127.0.0.1
        
    - name: Migrate database to Adonis and seed with data
      run: |
        cd server
        adonis run:migration  
        adonis seed
        
    - name: Run backend
      run: |
        cd server
        adonis serve
